spring:
  application:
    name: MyAppointments
    prefix: ap-azure
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://az-db-creds.vault.azure.net/
  datasource:
    url: jdbc:sqlserver://${DB_SERVER}.database.windows.net:1433;database=${DB_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        format_sql: false
    show-sql: false

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    root: WARN
    com.jb.appointments: INFO
